# Generated by Django 5.2 on 2025-05-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='xp_earned',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='total_xp',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
