# Generated by Django 5.2 on 2025-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_studentprogress_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grading_period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('prefinal', 'Prefinal'), ('final', 'Final')], default='prelim', max_length=10),
        ),
    ]
