# Generated by Django 5.2.1 on 2025-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recitation_percent',
            field=models.FloatField(default=0.0, help_text='Recitation percent (0-100)'),
        ),
    ]
