# Generated by Django 5.2 on 2025-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('2400', '2400'), ('2406', '2406'), ('2412', '2412')], max_length=4, null=True),
        ),
    ]
