# Generated by Django 5.2 on 2025-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='locked',
            field=models.BooleanField(default=False, help_text='Lock this exam for non-admin users'),
        ),
    ]
