# Generated by Django 5.2 on 2025-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Mark this exam as published (visible to students and locked for editing).'),
        ),
    ]
