# Generated by Django 5.2 on 2025-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='partial_score',
            field=models.PositiveIntegerField(default=0, help_text='Number of correct blanks for fill-in-the-blanks questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('identification', 'Identification'), ('fill_in_the_blanks', 'Fill in the Blanks')], default='multiple_choice', max_length=20),
        ),
    ]
