# Generated by Django 5.2 on 2025-05-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Mark this quiz as published (visible to students and locked for editing).'),
        ),
    ]
